server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: zuul-service-filter

zuul:
  routes:
    api:
      path: /**
      serviceId: eureka-provider