server:
  port: 8088

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: config-client
  cloud:
    config:
      label: master
      profile: dev
      uri: http://localhost:8888/

#  spring.cloud.config.label 指明远程仓库的分支
#  spring.cloud.config.profile
#  dev开发环境配置文件
#  test测试环境
#  pro正式环境
#  spring.cloud.config.uri= http://localhost:8888/ 指明配置服务中心的网址。